#!/usr/bin/env bash
# Regenerates the Xcode project.
#
#   ./bootstrap.sh          Mac only, ad-hoc signed. No Apple account needed.
#   ./bootstrap.sh --ios    Adds iPhone/iPad. Requires an Apple ID signed in under
#                           Xcode > Settings > Accounts, since device builds need a
#                           real provisioning profile.
#
# The app sources are already universal — this only flips destinations and signing.
set -euo pipefail
cd "$(dirname "$0")"

command -v xcodegen >/dev/null || { echo "xcodegen missing: brew install xcodegen" >&2; exit 1; }

# Both helpers rewrite marked lines in project.yml so the spec stays the single
# source of truth rather than being duplicated per platform.
set_destinations() {
  /usr/bin/sed -i '' "s|^    supportedDestinations: .*|    supportedDestinations: $1|" project.yml
}

set_signing() {
  if [ "$1" = "automatic" ]; then
    /usr/bin/sed -i '' \
      -e 's|^    CODE_SIGN_STYLE: Manual|    CODE_SIGN_STYLE: Automatic|' \
      -e 's|^    CODE_SIGN_IDENTITY: "-"|    CODE_SIGN_IDENTITY: "Apple Development"|' project.yml
    grep -q '^configFiles:' project.yml || /usr/bin/sed -i '' \
      's|^settings:|configFiles:\
  Debug: Local.xcconfig\
  Release: Local.xcconfig\
\
settings:|' project.yml
  else
    /usr/bin/sed -i '' \
      -e 's|^    CODE_SIGN_STYLE: Automatic|    CODE_SIGN_STYLE: Manual|' \
      -e 's|^    CODE_SIGN_IDENTITY: "Apple Development"|    CODE_SIGN_IDENTITY: "-"|' project.yml
    /usr/bin/sed -i '' '/^configFiles:/,+3d' project.yml
  fi
}

if [ "${1:-}" = "--ios" ]; then
  TEAM=$(security find-identity -v -p codesigning | sed -n 's/.*(\([A-Z0-9]\{10\}\)).*/\1/p' | head -1)
  if [ -z "$TEAM" ]; then
    echo "No codesigning identity found." >&2
    echo "Open Xcode > Settings > Accounts, add your Apple ID, then re-run." >&2
    exit 1
  fi
  printf '// Generated by bootstrap.sh --ios; gitignored.\nDEVELOPMENT_TEAM = %s\n' "$TEAM" > Local.xcconfig
  set_destinations '[macOS, iOS]'
  set_signing automatic
  echo "iOS enabled (team $TEAM)."
  echo "First device build needs: xcodebuild -allowProvisioningUpdates ..."
else
  rm -f Local.xcconfig
  set_destinations '[macOS]'
  set_signing adhoc
fi

xcodegen generate
